apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: counter
  name: counter
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: counter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: counter
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        name: demo-nsearch
        env:
        - name: {{ .Values.env.variable }}
          value: {{ .Values.env.value | quote }}
        resources: {}
status: {}
