apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: counter
  name: counter-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: counter
status:
  loadBalancer: {}